AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'gemfiles/*.gemfile'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - '*.gemspec'

Layout/LineLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Naming/PredicateMethod:
  Enabled: false
