---
"on":
  push:
    tags:
      - v*

name: Push Gem
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: rubygems/configure-rubygems-credentials@dc5a8d8553e6ee01fc26761a49e99e733d17954a # v2.1.0
        with:
          role-to-assume: ${{ secrets.RUBYGEMS_PUSH_ROLE }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set remote URL
        run: |
          # Attribute commits to the last committer on HEAD
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          bundler-cache: false
          ruby-version: ruby
      - name: Install dependencies
        run: bundle install
      - name: Release
        run: bundle exec rake release
      - name: Wait for release to propagate
        run: |
          gem install rubygems-await
          gem_tuple="$(ruby -rbundler/setup -rbundler -e '
              spec = Bundler.definition.specs.find {|s| s.name == ARGV[0] }
              raise "No spec for #{ARGV[0]}" unless spec
              print [spec.name, spec.version, spec.platform].join(":")
            ' "jwt")"
          gem await "${gem_tuple}"
